# This is for dev purposes only!

services:
  # PostgreSQL Service
  db:
    image: postgres:16.4
    container_name: web-reader-db
    restart: unless-stopped
    tty: true
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: gvary
      POSTGRES_USER: gvary-user
      POSTGRES_PASSWORD: gvary-pwd
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - gvary-network
  mailpit:
    image: axllent/mailpit
    container_name: web-reader-mailpit
    restart: unless-stopped
    ports:
      - '8025:8025'
      - '1025:1025'
networks:
  gvary-network:
    driver: bridge

volumes:
  db-volume:
    driver: local
